language: python

notifications:
  email:
    on_success: never

cache:
  directories:
    - $HOME/.cache/pip

env:
  - IMGAUG_NO_CV2_INSTALLED_CHECK=TRUE

matrix:
  include:
    - python: 2.7
      env: PYTORCH_WHEEL=https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp27-cp27mu-linux_x86_64.whl
    - python: 3.5
      env: PYTORCH_WHEEL=https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp35-cp35m-linux_x86_64.whl
    - python: 3.6
      env: PYTORCH_WHEEL=https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp36-cp36m-linux_x86_64.whl
    - python: 3.6
      env: TEST_MODE=DOCS
    - python: 3.7
      env: PYTORCH_WHEEL=https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp37-cp37m-linux_x86_64.whl
      dist: xenial
      sudo: true

install:
- pip install --upgrade pip pytest
- if [[ "$TEST_MODE" == "DOCS" ]]; then pip install .; fi
- if [[ -n "$PYTORCH_WHEEL" ]]; then pip install "$PYTORCH_WHEEL" torchvision; fi
- if [[ "$TEST_MODE" != "DOCS" ]]; then pip install .[tests]; fi
- if [[ "$TEST_MODE" != "DOCS" ]]; then pip install "pydocstyle<4.0.0" flake8 flake8-docstrings isort; fi

script:
  - if [[ "$TEST_MODE" == "DOCS" ]]; then python tools/make_transforms_docs.py check README.md; fi
  - if [[ "$TEST_MODE" != "DOCS" ]]; then pytest; fi
  - if [[ "$TEST_MODE" != "DOCS" ]]; then flake8; fi
  - if [[ "$TEST_MODE" != "DOCS" ]]; then isort -rc --check-only; fi
